### ISSUE TITLE
`subtract()` and maybe other methods relying on old file signals are broken

### ISSUE THREAD

**Issue by dberenbaum** [iterative/datachain#103]
### Description

Example to reproduce:

```python
>>> from datachain import C, DataChain
>>> source = "gs://dvcx-datalakes/dogs-and-cats/"
>>> chain = DataChain.from_storage(source)
>>> chain.subtract(chain.limit(5)).collect()
Listing gs://dvcx-datalakes: 400 objects [00:00, 1214.35 objects/s]
Processed: 400 rows [00:00, 13201.67 rows/s]
Processed: 400 rows [00:00, 25120.48 rows/s]
Traceback (most recent call last):
  File "/Users/dave/micromamba/envs/dvcx-py311/lib/python3.11/site-packages/sqlalchemy/sql/base.py", line 1617, in __getattr__
    return self._index[key][1]
           ~~~~~~~~~~~^^^^^
KeyError: 'source'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dave/Code/datachain/src/datachain/lib/dc.py", line 774, in collect
    return list(self.iterate(*cols))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/datachain/src/datachain/lib/dc.py", line 757, in iterate
    with super().select(*db_signals).as_iterable() as rows:
  File "/Users/dave/micromamba/envs/dvcx-py311/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/dave/Code/datachain/src/datachain/query/dataset.py", line 1251, in as_iterable
    query = self.apply_steps().select()
            ^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/datachain/src/datachain/query/dataset.py", line 1191, in apply_steps
    result = step.apply(
             ^^^^^^^^^^^
  File "/Users/dave/Code/datachain/src/datachain/query/dataset.py", line 278, in apply
    diff_q = self.query(source_query, target_query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/datachain/src/datachain/query/dataset.py", line 310, in query
    return self.catalog.warehouse.subtract_query(source_query, target_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Code/datachain/src/datachain/data_storage/warehouse.py", line 924, in subtract_query
    (sq.c.source == tq.c.source)
     ^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/dvcx-py311/lib/python3.11/site-packages/sqlalchemy/sql/base.py", line 1619, in __getattr__
    raise AttributeError(key) from err
AttributeError: source
```

It looks like parts of the codebase still rely on the old file signals which have now been dropped. This breaks examples like https://github.com/iterative/datachain/blob/main/examples/computer_vision/fashion_product_images/4-inference.ipynb.

### Version Info

```Text
0.2.10.dev6+gcc0b63b.d20240716
Python 3.11.0
```

**Comment by mattseddon** [comment]
you are right @rlamy it is a weird notebook bug, I cannot recreate the error with a simple example. Sorry
