### ISSUE TITLE
Parallel processing with UDFs broken

### ISSUE THREAD

**Issue by tibor-mach** [iterative/datachain#334]
### Description

I try to run the example script for parallel processing [here](https://github.com/iterative/datachain/blob/main/examples/get_started/udfs/parallel.py) and it returns the following error. It looks like some dependencies are missing.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/tibor/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/__main__.py", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tibor/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/cli.py", line 931, in main
    from datachain.query.dispatch import udf_entrypoint
  File "/home/tibor/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/query/dispatch.py", line 22, in <module>
    from datachain.query.queue import (
  File "/home/tibor/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/query/queue.py", line 8, in <module>
    import msgpack
ModuleNotFoundError: No module named 'msgpack'
Cleanup: 4 tables [00:00, 3056.52 tables/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], [line 39](vscode-notebook-cell:?execution_count=1&line=39)
     [29](vscode-notebook-cell:?execution_count=1&line=29)     return len(path)
     [32](vscode-notebook-cell:?execution_count=1&line=32) # Run in chain
     [33](vscode-notebook-cell:?execution_count=1&line=33) DataChain.from_storage(
     [34](vscode-notebook-cell:?execution_count=1&line=34)     path="gs://datachain-demo/dogs-and-cats/",
     [35](vscode-notebook-cell:?execution_count=1&line=35) ).settings(parallel=-1).map(
     [36](vscode-notebook-cell:?execution_count=1&line=36)     path_len_benchmark,
     [37](vscode-notebook-cell:?execution_count=1&line=37)     params=["file.path"],
     [38](vscode-notebook-cell:?execution_count=1&line=38)     output={"path_len": int},
---> [39](vscode-notebook-cell:?execution_count=1&line=39) ).show()

File ~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1252, in DataChain.show(self, limit, flatten, transpose, truncate)
   [1243](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1243) """Show a preview of the chain results.
   [1244](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1244) 
   [1245](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1245) Parameters:
   (...)
   [1249](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1249)     truncate : Whether or not to truncate the contents of columns.
   [1250](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1250) """
   [1251](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1251) dc = self.limit(limit) if limit > 0 else self
-> [1252](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1252) df = dc.to_pandas(flatten)
   [1254](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1254) if df.empty:
   [1255](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/lib/dc.py:1255)     print("Empty result")
...
    [532](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/query/dataset.py:532)     # Otherwise process single-threaded (faster for smaller UDFs)
    [533](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/query/dataset.py:533)     # Optionally instantiate the UDF instance if a class is provided.
    [534](https://file+.vscode-resource.vscode-cdn.net/home/tibor/Repos/datachain-examples/~/Repos/datachain-examples/.venv/lib64/python3.12/site-packages/datachain/query/dataset.py:534)     if isinstance(self.udf, UDFFactory):

RuntimeError: UDF Execution Failed!
```

### Version Info

```Text
0.3.4
Python 3.12.4
```

**Comment by mattseddon** [comment]
From the stack trace: `ModuleNotFoundError: No module named 'msgpack'`. 

The `pyproject.toml` shows that `msgpack` is part of the `remote` optional dependencies. The `examples` optional dependencies are there as a quickstart. They install all optional dependencies plus some extra ones which are only required by specific examples.

**Comment by mattseddon** [comment]
do you mean - "why is a package required for parallel processing, not a core dependency?"?

**Comment by mattseddon** [comment]
¯\_(ツ)_/¯
