### ISSUE TITLE
select_except() does not support sub-classes

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#637]
### Description

For some reason I cannot select_except() a class (`yolo`) while a sub-class was created (`my_poses`).

Note, if I won't have a subclass my_poses - it will except the whole yolo just fine. But we still need to support the case when only a subclass left.

```python
from io import BytesIO

from PIL import Image
from ultralytics import YOLO
from datachain import DataChain, DataModel, C, File, model


class MyYolo(DataModel):
    bbox: model.ultralytics.YoloBBoxes
    segm: model.ultralytics.YoloSegments
    poses: model.ultralytics.YoloPoses


def process(yolo:YOLO, yolo_segm: YOLO, yolo_pose: YOLO, file: File) -> MyYolo:
    img = Image.open(BytesIO(file.read()))
    return MyYolo(
        bbox=model.ultralytics.YoloBBoxes.from_results(yolo(img, verbose=False)),
        segm=model.ultralytics.YoloSegments.from_results(yolo_segm(img, verbose=False)),
        poses=model.ultralytics.YoloPoses.from_results(yolo_pose(img, verbose=False))
    )


(
    DataChain
    .from_storage("gs://mpii-human-pose")
    .limit(10)
    .setup(
        yolo=lambda: YOLO("yolo11n.pt"),
        yolo_segm=lambda: YOLO("yolo11n-seg.pt"),
        yolo_pose=lambda: YOLO("yolo11n-pose.pt")
    )
    .map(yolo=process)
  	.mutate(my_poses=C("yolo.poses"))
  	.select_except("yolo")
    .save("yolo_mpii")
)
```

Error:
```
Preparing: 10 rows [00:00, 3952.42 rows/s]
Download: 5.46MB [00:05, 1.02MB/s]
Processed: 10 rows [00:04,  2.49 rows/s]
Cleanup: 2 tables [00:00, 3278.08 tables/s]
Traceback (most recent call last):
  File "/Users/dmitry/src/datachain/yolo_test.py", line 24, in <module>
    DataChain
  File "/Users/dmitry/venv/venv-py39/lib/python3.9/site-packages/datachain/lib/dc.py", line 818, in save
    query=self._query.save(
  File "/Users/dmitry/venv/venv-py39/lib/python3.9/site-packages/datachain/query/dataset.py", line 1577, in save
    query = self.apply_steps()
  File "/Users/dmitry/venv/venv-py39/lib/python3.9/site-packages/datachain/query/dataset.py", line 1126, in apply_steps
    result = step.apply(
  File "/Users/dmitry/venv/venv-py39/lib/python3.9/site-packages/datachain/query/dataset.py", line 679, in apply
    new_query = self.apply_sql_clause(query)
  File "/Users/dmitry/venv/venv-py39/lib/python3.9/site-packages/datachain/query/dataset.py", line 698, in apply_sql_clause
    args = [subquery.c[str(c)] if isinstance(c, (str, C)) else c for c in self.args]
  File "/Users/dmitry/venv/venv-py39/lib/python3.9/site-packages/datachain/query/dataset.py", line 698, in <listcomp>
    args = [subquery.c[str(c)] if isinstance(c, (str, C)) else c for c in self.args]
  File "/Users/dmitry/venv/venv-py39/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1608, in __getitem__
    return self._index[key][1]
KeyError: 'my_poses'
```

### Version Info

```Text
0.7.1
Python 3.9.16
```

**Comment by dreadatour** [comment]
Looks like the issue was in `mutate` method. Fix is here: https://github.com/iterative/datachain/pull/658
