### ISSUE TITLE
When UDF fails we don't print any details from query code

### ISSUE THREAD

**Issue by shcheklein** [iterative/datachain#663]
![Image](https://github.com/user-attachments/assets/d4f1ac57-9f6c-4331-9984-eaba12b93071)

And that's pretty much it.

It's weird that sometimes I can actually see some messages, but not in this case.

**Comment by shcheklein** [comment]
Can we do the basic research? If it fails see if we print stack trace, if fails to start for some reason also, etc.

**Comment by shcheklein** [comment]
Okay, the difference might be `parallel` flag. Let's check if in parallel mode we are getting actual results.

**Comment by skshetry** [comment]
Is there any output before the traceback?

**Comment by shcheklein** [comment]
yes, but it's primarily the same - stack trace to `save()` function or something (kinda `dc` internal stack trace, no details)

**Comment by skshetry** [comment]
@shcheklein, can you please provide a reproducible code here? I tried the following code snippet and I could see an exception.

```python
from datachain import DataChain


# Define the UDF:
def path_len(path):
    raise ValueError("This is an error")


if __name__ == "__main__":
    # Run in chain
    DataChain.from_storage(
        uri="gs://datachain-demo/dogs-and-cats/",
    ).map(
        path_len,
        params=["file.path"],
        output={"path_len": int},
    ).show()
```

<details><summary>Output</summary>
<p>

```pytb
Processed: 0 rows [00:00, ? rows/s]
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
============== Error in user code: 'Mapper' ==============                                                                                           
Traceback (most recent call last):                                
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 174, in process
    return self._func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/examples/get_started/udfs/simple.py", line 6, in path_len
    raise ValueError("This is an error")
ValueError: This is an error
==========================================================
Traceback (most recent call last):                                                                                                                   
  File "/Users/saugat/Projects/iterative/datachain/examples/get_started/udfs/simple.py", line 17, in <module>
    ).show()
      ^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/dc.py", line 1872, in show
    df = dc.to_pandas(flatten, include_hidden=include_hidden)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/dc.py", line 1849, in to_pandas
    results = self.results(include_hidden=include_hidden)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/dc.py", line 1319, in results
    return list(self.collect_flatten(include_hidden=include_hidden))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/dc.py", line 1270, in collect_flatten
    with self._query.ordered_select(*db_signals).as_iterable() as rows:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Library/Application Support/uv/python/cpython-3.12.9-macos-x86_64-none/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 1262, in as_iterable
    query = self.apply_steps().select()
            ^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 1208, in apply_steps
    result = step.apply(
             ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 602, in apply
    self.populate_udf_table(udf_table, query)
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 520, in populate_udf_table
    process_udf_outputs(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 340, in process_udf_outputs
    for udf_output in udf_results:
                      ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 100, in run
    yield from self.inner.run(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 386, in run
    result_objs = self.process_safe(udf_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 284, in process_safe
    raise DataChainError(
datachain.lib.utils.DataChainError: Error in user code in class 'Mapper': This is an error
```

</p>
</details>

**Comment by shcheklein** [comment]
@skshetry have you tried to run it in the parallel mode? https://github.com/iterative/datachain/issues/663#issuecomment-2518784024 ?

**Comment by skshetry** [comment]
> [@skshetry](https://github.com/skshetry) have you tried to run it in the parallel mode? [#663 (comment)](https://github.com/iterative/datachain/issues/663#issuecomment-2518784024) ?

yes, I did. I get a very lengthy output (see #742).

<details><summary>Output</summary>
<p>

```pytb
Processed: 0 rows [00:00, ? rows/s]
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
============== Error in user code: 'Mapper' ==============                                                                                           
Traceback (most recent call last):                                
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 174, in process
    return self._func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/script.py", line 6, in path_len
    raise ValueError("This is an error")
ValueError: This is an error
==========================================================
Process Worker-UDF-0:
Traceback (most recent call last):
  File "/Users/saugat/Projects/iterative/datachain/.venv/lib/python3.12/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/saugat/Projects/iterative/datachain/.venv/lib/python3.12/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 146, in _run_worker
    worker.run()
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 321, in run
    process_udf_outputs(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 340, in process_udf_outputs
    for udf_output in udf_results:
                      ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 335, in notify_and_process
    for row in udf_results:
               ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 100, in run
    yield from self.inner.run(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 386, in run
    result_objs = self.process_safe(udf_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 284, in process_safe
    raise DataChainError(
datachain.lib.utils.DataChainError: Error in user code in class 'Mapper': This is an error
============== Error in user code: 'Mapper' ==============
Traceback (most recent call last):
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 174, in process
    return self._func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/script.py", line 6, in path_len
    raise ValueError("This is an error")
ValueError: This is an error
==========================================================
Process Worker-UDF-1:
Traceback (most recent call last):
  File "/Users/saugat/Projects/iterative/datachain/.venv/lib/python3.12/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/saugat/Projects/iterative/datachain/.venv/lib/python3.12/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 146, in _run_worker
    worker.run()
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 321, in run
    process_udf_outputs(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 340, in process_udf_outputs
    for udf_output in udf_results:
                      ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 335, in notify_and_process
    for row in udf_results:
               ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 100, in run
    yield from self.inner.run(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 386, in run
    result_objs = self.process_safe(udf_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 284, in process_safe
    raise DataChainError(
datachain.lib.utils.DataChainError: Error in user code in class 'Mapper': This is an error
============== Error in user code: 'Mapper' ==============
Traceback (most recent call last):
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 174, in process
    return self._func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/script.py", line 6, in path_len
    raise ValueError("This is an error")
ValueError: This is an error
==========================================================
Process Worker-UDF-2:
Traceback (most recent call last):
  File "/Users/saugat/Projects/iterative/datachain/.venv/lib/python3.12/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/saugat/Projects/iterative/datachain/.venv/lib/python3.12/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 146, in _run_worker
    worker.run()
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 321, in run
    process_udf_outputs(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 340, in process_udf_outputs
    for udf_output in udf_results:
                      ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 335, in notify_and_process
    for row in udf_results:
               ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 100, in run
    yield from self.inner.run(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 386, in run
    result_objs = self.process_safe(udf_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 284, in process_safe
    raise DataChainError(
datachain.lib.utils.DataChainError: Error in user code in class 'Mapper': This is an error
============== Error in user code: 'Mapper' ==============
Traceback (most recent call last):
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 174, in process
    return self._func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/script.py", line 6, in path_len
    raise ValueError("This is an error")
ValueError: This is an error
==========================================================
Process Worker-UDF-3:
Traceback (most recent call last):
  File "/Users/saugat/Projects/iterative/datachain/.venv/lib/python3.12/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/saugat/Projects/iterative/datachain/.venv/lib/python3.12/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 146, in _run_worker
    worker.run()
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 321, in run
    process_udf_outputs(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 340, in process_udf_outputs
    for udf_output in udf_results:
                      ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 335, in notify_and_process
    for row in udf_results:
               ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 100, in run
    yield from self.inner.run(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 386, in run
    result_objs = self.process_safe(udf_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/udf.py", line 284, in process_safe
    raise DataChainError(
datachain.lib.utils.DataChainError: Error in user code in class 'Mapper': This is an error
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/__main__.py", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/cli/__init__.py", line 39, in main
    return handle_udf(args.command)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/cli/__init__.py", line 309, in handle_udf
    return udf_entrypoint()
           ^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 82, in udf_entrypoint
    dispatch.run_udf_parallel(
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dispatch.py", line 232, in run_udf_parallel
    raise exc
datachain.lib.utils.DataChainError: Error in user code in class 'Mapper': This is an error
Traceback (most recent call last):                                                                                                                   
  File "/Users/saugat/Projects/iterative/datachain/script.py", line 17, in <module>
    ).show()
      ^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/dc.py", line 1872, in show
    df = dc.to_pandas(flatten, include_hidden=include_hidden)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/dc.py", line 1849, in to_pandas
    results = self.results(include_hidden=include_hidden)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/dc.py", line 1319, in results
    return list(self.collect_flatten(include_hidden=include_hidden))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/lib/dc.py", line 1270, in collect_flatten
    with self._query.ordered_select(*db_signals).as_iterable() as rows:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Library/Application Support/uv/python/cpython-3.12.9-macos-x86_64-none/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 1262, in as_iterable
    query = self.apply_steps().select()
            ^^^^^^^^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 1208, in apply_steps
    result = step.apply(
             ^^^^^^^^^^^
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 602, in apply
    self.populate_udf_table(udf_table, query)
  File "/Users/saugat/Projects/iterative/datachain/src/datachain/query/dataset.py", line 498, in populate_udf_table
    raise RuntimeError(
RuntimeError: UDF Execution Failed! Exit code: 1
```

</p>
</details>

**Comment by shcheklein** [comment]
okay, something might have changed then. Let's close this and come back when I / someone hits this again.
